let data = [
  {
    blob: 'I',
    type: 'Industrial',
    img: 'https://www.argosy.co.nz/assets/property-images/729-120419_ARGOSY_MIGHTYAPE_7__FocusFillWzEwODAsNjAwLCJ5Iiw1NV0.jpg',
    protertyName: 'Highgate Parkway, Silverdale',
    org: 'Auckland',
    inductor: 'This property is 22,575sqm of land which is occupied by Mighty Ape’s new 10,500 sqm distribution centre. Thisbuilding was New Zealands 3rd 5 Green Star Industrial Built building. The main energy efficient features are LED lightswithdaylight and occupancy sensors, Increased fresh air rates with CO2 control and air to air heat recovery, heatrecoveryVRF heating and cooling system, low VOC flooring, adhesives and sealants, sustainable timber and peak energydemandreduction.',
    Valuation: '$36,450,000',
    WALT: '6.9',
    Area: '10,581',
    Yield: '4.80%',
    position: 'PROPERTY MANAGER',
    positionName: "Anne Staub",
    tel: '021 488 397',
    peoImg: 'https://www.argosy.co.nz/assets/people-images/45I1751_sm-ANNE__FocusFillWzEyMCwxMjAsIngiLDMwXQ.jpg'
  },
  {
    blob: 'I',
    type: 'Industrial',
    img: 'https://www.argosy.co.nz/assets/property-images/45I1526_low_res__FocusFillWzEwODAsNjAwLCJ5Iiw2MF0.jpg',
    protertyName: '1 Rothwell Avenue, Albany',
    org: 'Auckland',
    inductor: 'The property comprises a large industrial building constructed circa 1984 providing expansive areas of warehouse with associated recently refurbished offices and showroom.',
    Valuation: '$36,700,000',
    WALT: '9.3',
    Area: '12,683',
    Yield: '4.62%',
    position: 'PROPERTY MANAGER',
    positionName: "Anne Staub",
    tel: '021 488 397',
    peoImg: 'https://www.argosy.co.nz/assets/people-images/45I1751_sm-ANNE__FocusFillWzEyMCwxMjAsIngiLDMwXQ.jpg'
  },
  {
    blob: 'I',
    type: 'Industrial',
    img: 'https://www.argosy.co.nz/assets/property-images/870_ARGOSY_4_HENDERSON_PL_001_lowres__FocusFillWzEwODAsNjAwLCJ5IiwxNF0.jpg',
    protertyName: '4 Henderson Place, Onehunga',
    org: 'Auckland',
    inductor: 'The property comprises a substantial industrial facility constructed in 1987 and refurbished in 2017. The improvements include a large sprinklered double gable warehouse, two levels of offices, a large canopy and sealed yard area to the northern and eastern portion of the site. The property comprises a large land holding of 21,860 sqm to the eastern periphery of Onehunga, with dual access from Henderson Place and secondary access provided via right of way off Mays Road.',
    Valuation: '$32,600,000',
    WALT: '10.3',
    Area: '10,841',
    Yield: '4.98%',
    position: 'PROPERTY MANAGER',
    positionName: "Meera Sima",
    tel: '021 488 075',
    peoImg: "https://www.argosy.co.nz/assets/people-images/Capture2__FocusFillWzEyMCwxMjAsInkiLDI2XQ.JPG"
  },
  {
    blob: 'I',
    type: 'Industrial',
    img: 'https://www.argosy.co.nz/assets/property-images/871-2E1A3411-copy__FocusFillWzEwODAsNjAwLCJ5Iiw2MF0.jpg',
    protertyName: '320 Ti Rakau Drive, East Tamaki',
    org: 'Auckland',
    inductor: 'A mixed use complex which incorporates a large distribution warehouse, together with trade retail, offices and a smaller freestanding bulk retail premise. The property is situated with extensive frontage to Ti Rakau Drive, benefitting from resulting exposure.',
    Valuation: '$81,700,000',
    WALT: '6.9',
    Area: '28,353',
    Yield: '5.08%',
    position: 'PROPERTY MANAGER',
    positionName: "Amy Myocevich",
    tel: '021 959 922',
    peoImg: 'https://www.argosy.co.nz/assets/people-images/45I1782_sm-AMY__FocusFillWzEyMCwxMjAsIngiLDMwXQ.jpg'
  },
  {
    blob: 'O',
    type: 'Office',
    img: 'https://www.argosy.co.nz/assets/property-images/1-623685-01__FocusFillWzE0NjAsMTEwMCxmYWxzZSwwXQ.jpg',
    protertyName: '8 Nugent Street, Grafton',
    org: 'Auckland',
    inductor: 'The property was built in 2009 and is a five level, 4 Green Star designed office building.',
    Valuation: '$55,500,000',
    WALT: '3.3',
    Area: '8,125',
    Yield: '325',
    position: 'PROPERTY MANAGER',
    positionName: "Anne Staub",
    tel: '021 488 397',
    peoImg: 'https://www.argosy.co.nz/assets/people-images/45I1751_sm-ANNE__FocusFillWzEyMCwxMjAsIngiLDMwXQ.jpg'
  },
  {
    blob: 'O',
    type: 'Office',
    img: 'https://www.argosy.co.nz/assets/property-images/1-901-39-Market-Place__FocusFillWzE0NjAsMTEwMCxmYWxzZSwwXQ.jpg',
    protertyName: '39 Market Place, Viaduct Harbour',
    org: 'Auckland',
    inductor: 'The property was originally the Auckland City Council municipal markets built during WW1. It now provides character office accommodation with basement carparking.',
    Valuation: '$42,500,000',
    WALT: '3.7',
    Area: '10,365',
    Yield: '675',
    position: 'PROPERTY MANAGER',
    positionName: "Anne Staub",
    tel: '021 488 397',
    peoImg: 'https://www.argosy.co.nz/assets/people-images/45I1751_sm-ANNE__FocusFillWzEyMCwxMjAsIngiLDMwXQ.jpg'
  },
  {
    blob: 'O',
    type: 'Office',
    img: 'https://www.argosy.co.nz/assets/property-images/45I1355__FocusFillWzE0NjAsMTEwMCwieCIsOTRd.jpg',
    protertyName: '107 Carlton Gore Road, Newmarket',
    org: 'Auckland',
    inductor: 'A modern 5 star GREEN office building offering an above average standard of accommodation, together with basement carparking. The property recently enjoyed a comprehensive full building upgrade. It occupies a prominent road frontage position upon Carlton Gore Road within an established precinct of office building that enjoy proximity to a number of arterial routes.',
    Valuation: '$46,800,000',
    WALT: '10.9',
    Area: '6,093',
    Yield: '5.56%',
    position: 'PROPERTY MANAGER',
    positionName: "Amy Myocevich",
    tel: '021 959 922',
    peoImg: 'https://www.argosy.co.nz/assets/people-images/45I1782_sm-AMY__FocusFillWzEyMCwxMjAsIngiLDMwXQ.jpg'
  },
  {
    blob: 'O',
    type: 'Office',
    img: 'https://www.argosy.co.nz/assets/property-images/1-5598-ArgosyVector2014__FocusFillWzE0NjAsMTEwMCxmYWxzZSwwXQ.jpg',
    protertyName: '101 Carlton Gore Road, Newmarket',
    org: 'Auckland',
    inductor: 'AA single tenanted, modern office building located in Newmarket, surrounded by quality commercial office blocks with great views of the Auckland Domain. The property has five levels of office space with carparking over two levels. ',
    Valuation: '$29,500,000',
    WALT: '2.6',
    Area: '4,821',
    Yield: '6.12%',
    position: 'PROPERTY MANAGER',
    positionName: "Amy Myocevich",
    tel: '021 959 922',
    peoImg: 'https://www.argosy.co.nz/assets/people-images/45I1782_sm-AMY__FocusFillWzEyMCwxMjAsIngiLDMwXQ.jpg'
  },
  {
    blob: 'R',
    type: 'Retial',
    img: 'https://www.argosy.co.nz/assets/property-images/056-Albany-Mega-Centre-9031__FocusFillWzE0NjAsMTEwMCxmYWxzZSwwXQ.jpg',
    protertyName: 'Albany Mega Centre & 11 Coliseum Drive, Albany',
    org: 'Auckland',
    inductor: `The property enjoys good exposure to State Highway 17 and benefits significantly from surrounding retail outlets. The premises consist of a modern 'u' shaped bulk retail complex providing individual tenancies with sizes between 350sqm and 3,300sqm. Carparking provided is of a reasonable ratio for a centre of this size. This property includes The Warehouse -located adjacent to the Mega Centre and comprises 7,600sqm of warehouse, 760sqm of office, mezzanine and garden centre and 413 dedicated carparks.`,
    Valuation: '$160,000,000',
    WALT: '3.6',
    Area: '10,581',
    Yield: '5.75%',
    position: 'PROPERTY MANAGER',
    positionName: "Jeremy Koh",
    tel: '0212462857',
    peoImg: 'https://www.argosy.co.nz/assets/people-images/Jeremy-compressed__FocusFillWzEyMCwxMjAsInkiLDE4XQ.JPG'
  },
  {
    blob: 'R',
    type: 'Retial',
    img: 'https://www.argosy.co.nz/assets/property-images/715-DJI_0911_low_res__FocusFillWzE0NjAsMTEwMCwieCIsOTVd.jpg',
    protertyName: '252 Dairy Flat Highway, Albany',
    org: 'Auckland',
    inductor: 'The property comprises of four buildings, three of which are workshops used for servicing and parts storage. The front building is used as showroom/office and has been recently upgraded including a new canopy.',
    Valuation: '$10,300,000',
    WALT: '8.8',
    Area: '2,262',
    Yield: '4.94%',
    position: 'PROPERTY MANAGER',
    positionName: "Meera Sima",
    tel: '021 488 075',
    peoImg: "https://www.argosy.co.nz/assets/people-images/Capture2__FocusFillWzEyMCwxMjAsInkiLDI2XQ.JPG"
  },
  {
    blob: 'R',
    type: 'Retial',
    img: 'https://www.argosy.co.nz/assets/property-images/910-39-Cavendish-Drv-4256__FocusFillWzE0NjAsMTEwMCwieCIsOTRd.jpg',
    protertyName: '50 & 54-62 Cavendish Drive, Manukau',
    org: 'Auckland',
    inductor: 'A standalone bulk retail property purpose built for The Warehouse in 1996 with excellent exposure to Cavendish Drive.',
    Valuation: '$31,200,000',
    WALT: '4.2',
    Area: '9,939',
    Yield: '5.74%',
    position: 'PROPERTY MANAGER',
    positionName: "Meera Sima",
    tel: '021 488 075',
    peoImg: "https://www.argosy.co.nz/assets/people-images/Capture2__FocusFillWzEyMCwxMjAsInkiLDI2XQ.JPG"
  },
  {
    blob: 'R',
    type: 'Retial',
    img: 'https://www.argosy.co.nz/assets/property-images/1-41A2637-Edit__FocusFillWzE0NjAsMTEwMCxmYWxzZSwwXQ.jpg',
    protertyName: 'Cnr Taniwha & Paora Hapi Streets, Taupo',
    org: 'Auckland',
    inductor: 'A standalone bulk retail property located within a well established bulk retail area just north of the Central Business District of Taupo. The property boasts three street frontages with a lease in place to The Warehouse Limited.',
    Valuation: '$11,700,000',
    WALT: '1.5',
    Area: '4,212',
    Yield: '6.68%',
    position: 'PROPERTY MANAGER',
    positionName: "Ian Kilpatrick",
    tel: '021 812 546',
    peoImg: 'https://www.argosy.co.nz/assets/people-images/Ian-Kilpatrick__FocusFillWzEyMCwxMjAsIngiLDBd.jpg'
  },

]

export { data }