let data = [
  {
    img: 'https://www.argosy.co.nz/assets/property-images/729-120419_ARGOSY_MIGHTYAPE_7__FocusFillWzEwODAsNjAwLCJ5Iiw1NV0.jpg',
    protertyName: 'Highgate Parkway, Silverdale',
    org: 'Auckland',
    inductor: 'This property is 22,575sqm of land which is occupied by Mighty Ape’s new 10,500 sqm distribution centre. Thisbuilding was New Zealands 3rd 5 Green Star Industrial Built building. The main energy efficient features are LED lightswithdaylight and occupancy sensors, Increased fresh air rates with CO2 control and air to air heat recovery, heatrecoveryVRF heating and cooling system, low VOC flooring, adhesives and sealants, sustainable timber and peak energydemandreduction.',
    Valuation: '$36,450,000',
    WALT: '6.9',
    Area: '10,581',
    Yield: '4.80%',
    position: 'PROPERTY MANAGER',
    positionName: "Anne Staub",
    tel: '021 488 397',
    peoImg: 'https://www.argosy.co.nz/assets/people-images/45I1751_sm-ANNE__FocusFillWzEyMCwxMjAsIngiLDMwXQ.jpg'
  },
  {
    img: 'https://www.argosy.co.nz/assets/property-images/45I1526_low_res__FocusFillWzEwODAsNjAwLCJ5Iiw2MF0.jpg',
    protertyName: '1 Rothwell Avenue, Albany',
    org: 'Auckland',
    inductor: 'The property comprises a large industrial building constructed circa 1984 providing expansive areas of warehouse with associated recently refurbished offices and showroom.',
    Valuation: '$36,700,000',
    WALT: '9.3',
    Area: '12,683',
    Yield: '4.62%',
    position: 'PROPERTY MANAGER',
    positionName: "Anne Staub",
    tel: '021 488 397',
    peoImg: 'https://www.argosy.co.nz/assets/people-images/45I1751_sm-ANNE__FocusFillWzEyMCwxMjAsIngiLDMwXQ.jpg'
  },
  {
    img: 'https://www.argosy.co.nz/assets/property-images/870_ARGOSY_4_HENDERSON_PL_001_lowres__FocusFillWzEwODAsNjAwLCJ5IiwxNF0.jpg',
    protertyName: '4 Henderson Place, Onehunga',
    org: 'Auckland',
    inductor: 'The property comprises a substantial industrial facility constructed in 1987 and refurbished in 2017. The improvements include a large sprinklered double gable warehouse, two levels of offices, a large canopy and sealed yard area to the northern and eastern portion of the site. The property comprises a large land holding of 21,860 sqm to the eastern periphery of Onehunga, with dual access from Henderson Place and secondary access provided via right of way off Mays Road.',
    Valuation: '$32,600,000',
    WALT: '10.3',
    Area: '10,841',
    Yield: '4.98%',
    position: 'PROPERTY MANAGER',
    positionName: "Meera Sima",
    tel: '021 488 075',
    peoImg: "https://www.argosy.co.nz/assets/people-images/Capture2__FocusFillWzEyMCwxMjAsInkiLDI2XQ.JPG"
  },
  {
    img: 'https://www.argosy.co.nz/assets/property-images/871-2E1A3411-copy__FocusFillWzEwODAsNjAwLCJ5Iiw2MF0.jpg',
    protertyName: '320 Ti Rakau Drive, East Tamaki',
    org: 'Auckland',
    inductor: 'A mixed use complex which incorporates a large distribution warehouse, together with trade retail, offices and a smaller freestanding bulk retail premise. The property is situated with extensive frontage to Ti Rakau Drive, benefitting from resulting exposure.',
    Valuation: '$81,700,000',
    WALT: '6.9',
    Area: '28,353',
    Yield: '5.08%',
    position: 'PROPERTY MANAGER',
    positionName: "Amy Myocevich",
    tel: '021 959 922',
    peoImg: 'https://www.argosy.co.nz/assets/people-images/45I1782_sm-AMY__FocusFillWzEyMCwxMjAsIngiLDMwXQ.jpg'
  },
  {
    img: 'https://www.argosy.co.nz/assets/property-images/729-120419_ARGOSY_MIGHTYAPE_7__FocusFillWzEwODAsNjAwLCJ5Iiw1NV0.jpg',
    protertyName: 'Highgate Parkway, Silverdale',
    org: 'Auckland',
    inductor: 'This property is 22,575sqm of land which is occupied by Mighty Ape’s new 10,500 sqm distribution centre. Thisbuilding was New Zealands 3rd 5 Green Star Industrial Built building. The main energy efficient features are LED lightswithdaylight and occupancy sensors, Increased fresh air rates with CO2 control and air to air heat recovery, heatrecoveryVRF heating and cooling system, low VOC flooring, adhesives and sealants, sustainable timber and peak energydemandreduction.',
    Valuation: '$36,450,000',
    WALT: '6.9',
    Area: '10,581',
    Yield: '4.80%',
    position: 'PROPERTY MANAGER',
    positionName: "Anne Staub",
    tel: '021 488 397',
    peoImg: 'https://www.argosy.co.nz/assets/people-images/45I1751_sm-ANNE__FocusFillWzEyMCwxMjAsIngiLDMwXQ.jpg'
  },
  {
    img: 'https://www.argosy.co.nz/assets/property-images/45I1526_low_res__FocusFillWzEwODAsNjAwLCJ5Iiw2MF0.jpg',
    protertyName: '1 Rothwell Avenue, Albany',
    org: 'Auckland',
    inductor: 'The property comprises a large industrial building constructed circa 1984 providing expansive areas of warehouse with associated recently refurbished offices and showroom.',
    Valuation: '$36,700,000',
    WALT: '9.3',
    Area: '12,683',
    Yield: '4.62%',
    position: 'PROPERTY MANAGER',
    positionName: "Anne Staub",
    tel: '021 488 397',
    peoImg: 'https://www.argosy.co.nz/assets/people-images/45I1751_sm-ANNE__FocusFillWzEyMCwxMjAsIngiLDMwXQ.jpg'
  },
  {
    img: 'https://www.argosy.co.nz/assets/property-images/870_ARGOSY_4_HENDERSON_PL_001_lowres__FocusFillWzEwODAsNjAwLCJ5IiwxNF0.jpg',
    protertyName: '4 Henderson Place, Onehunga',
    org: 'Auckland',
    inductor: 'The property comprises a substantial industrial facility constructed in 1987 and refurbished in 2017. The improvements include a large sprinklered double gable warehouse, two levels of offices, a large canopy and sealed yard area to the northern and eastern portion of the site. The property comprises a large land holding of 21,860 sqm to the eastern periphery of Onehunga, with dual access from Henderson Place and secondary access provided via right of way off Mays Road.',
    Valuation: '$32,600,000',
    WALT: '10.3',
    Area: '10,841',
    Yield: '4.98%',
    position: 'PROPERTY MANAGER',
    positionName: "Meera Sima",
    tel: '021 488 075',
    peoImg: "https://www.argosy.co.nz/assets/people-images/Capture2__FocusFillWzEyMCwxMjAsInkiLDI2XQ.JPG"
  },
  {
    img: 'https://www.argosy.co.nz/assets/property-images/871-2E1A3411-copy__FocusFillWzEwODAsNjAwLCJ5Iiw2MF0.jpg',
    protertyName: '320 Ti Rakau Drive, East Tamaki',
    org: 'Auckland',
    inductor: 'A mixed use complex which incorporates a large distribution warehouse, together with trade retail, offices and a smaller freestanding bulk retail premise. The property is situated with extensive frontage to Ti Rakau Drive, benefitting from resulting exposure.',
    Valuation: '$81,700,000',
    WALT: '6.9',
    Area: '28,353',
    Yield: '5.08%',
    position: 'PROPERTY MANAGER',
    positionName: "Amy Myocevich",
    tel: '021 959 922',
    peoImg: 'https://www.argosy.co.nz/assets/people-images/45I1782_sm-AMY__FocusFillWzEyMCwxMjAsIngiLDMwXQ.jpg'
  },
  {
    img: 'https://www.argosy.co.nz/assets/property-images/729-120419_ARGOSY_MIGHTYAPE_7__FocusFillWzEwODAsNjAwLCJ5Iiw1NV0.jpg',
    protertyName: 'Highgate Parkway, Silverdale',
    org: 'Auckland',
    inductor: 'This property is 22,575sqm of land which is occupied by Mighty Ape’s new 10,500 sqm distribution centre. Thisbuilding was New Zealands 3rd 5 Green Star Industrial Built building. The main energy efficient features are LED lightswithdaylight and occupancy sensors, Increased fresh air rates with CO2 control and air to air heat recovery, heatrecoveryVRF heating and cooling system, low VOC flooring, adhesives and sealants, sustainable timber and peak energydemandreduction.',
    Valuation: '$36,450,000',
    WALT: '6.9',
    Area: '10,581',
    Yield: '4.80%',
    position: 'PROPERTY MANAGER',
    positionName: "Anne Staub",
    tel: '021 488 397',
    peoImg: 'https://www.argosy.co.nz/assets/people-images/45I1751_sm-ANNE__FocusFillWzEyMCwxMjAsIngiLDMwXQ.jpg'
  },
  {
    img: 'https://www.argosy.co.nz/assets/property-images/45I1526_low_res__FocusFillWzEwODAsNjAwLCJ5Iiw2MF0.jpg',
    protertyName: '1 Rothwell Avenue, Albany',
    org: 'Auckland',
    inductor: 'The property comprises a large industrial building constructed circa 1984 providing expansive areas of warehouse with associated recently refurbished offices and showroom.',
    Valuation: '$36,700,000',
    WALT: '9.3',
    Area: '12,683',
    Yield: '4.62%',
    position: 'PROPERTY MANAGER',
    positionName: "Anne Staub",
    tel: '021 488 397',
    peoImg: 'https://www.argosy.co.nz/assets/people-images/45I1751_sm-ANNE__FocusFillWzEyMCwxMjAsIngiLDMwXQ.jpg'
  },
  {
    img: 'https://www.argosy.co.nz/assets/property-images/870_ARGOSY_4_HENDERSON_PL_001_lowres__FocusFillWzEwODAsNjAwLCJ5IiwxNF0.jpg',
    protertyName: '4 Henderson Place, Onehunga',
    org: 'Auckland',
    inductor: 'The property comprises a substantial industrial facility constructed in 1987 and refurbished in 2017. The improvements include a large sprinklered double gable warehouse, two levels of offices, a large canopy and sealed yard area to the northern and eastern portion of the site. The property comprises a large land holding of 21,860 sqm to the eastern periphery of Onehunga, with dual access from Henderson Place and secondary access provided via right of way off Mays Road.',
    Valuation: '$32,600,000',
    WALT: '10.3',
    Area: '10,841',
    Yield: '4.98%',
    position: 'PROPERTY MANAGER',
    positionName: "Meera Sima",
    tel: '021 488 075',
    peoImg: "https://www.argosy.co.nz/assets/people-images/Capture2__FocusFillWzEyMCwxMjAsInkiLDI2XQ.JPG"
  },
  {
    img: 'https://www.argosy.co.nz/assets/property-images/871-2E1A3411-copy__FocusFillWzEwODAsNjAwLCJ5Iiw2MF0.jpg',
    protertyName: '320 Ti Rakau Drive, East Tamaki',
    org: 'Auckland',
    inductor: 'A mixed use complex which incorporates a large distribution warehouse, together with trade retail, offices and a smaller freestanding bulk retail premise. The property is situated with extensive frontage to Ti Rakau Drive, benefitting from resulting exposure.',
    Valuation: '$81,700,000',
    WALT: '6.9',
    Area: '28,353',
    Yield: '5.08%',
    position: 'PROPERTY MANAGER',
    positionName: "Amy Myocevich",
    tel: '021 959 922',
    peoImg: 'https://www.argosy.co.nz/assets/people-images/45I1782_sm-AMY__FocusFillWzEyMCwxMjAsIngiLDMwXQ.jpg'
  },
  {
    img: 'https://www.argosy.co.nz/assets/property-images/729-120419_ARGOSY_MIGHTYAPE_7__FocusFillWzEwODAsNjAwLCJ5Iiw1NV0.jpg',
    protertyName: 'Highgate Parkway, Silverdale',
    org: 'Auckland',
    inductor: 'This property is 22,575sqm of land which is occupied by Mighty Ape’s new 10,500 sqm distribution centre. Thisbuilding was New Zealands 3rd 5 Green Star Industrial Built building. The main energy efficient features are LED lightswithdaylight and occupancy sensors, Increased fresh air rates with CO2 control and air to air heat recovery, heatrecoveryVRF heating and cooling system, low VOC flooring, adhesives and sealants, sustainable timber and peak energydemandreduction.',
    Valuation: '$36,450,000',
    WALT: '6.9',
    Area: '10,581',
    Yield: '4.80%',
    position: 'PROPERTY MANAGER',
    positionName: "Anne Staub",
    tel: '021 488 397',
    peoImg: 'https://www.argosy.co.nz/assets/people-images/45I1751_sm-ANNE__FocusFillWzEyMCwxMjAsIngiLDMwXQ.jpg'
  },
  {
    img: 'https://www.argosy.co.nz/assets/property-images/45I1526_low_res__FocusFillWzEwODAsNjAwLCJ5Iiw2MF0.jpg',
    protertyName: '1 Rothwell Avenue, Albany',
    org: 'Auckland',
    inductor: 'The property comprises a large industrial building constructed circa 1984 providing expansive areas of warehouse with associated recently refurbished offices and showroom.',
    Valuation: '$36,700,000',
    WALT: '9.3',
    Area: '12,683',
    Yield: '4.62%',
    position: 'PROPERTY MANAGER',
    positionName: "Anne Staub",
    tel: '021 488 397',
    peoImg: 'https://www.argosy.co.nz/assets/people-images/45I1751_sm-ANNE__FocusFillWzEyMCwxMjAsIngiLDMwXQ.jpg'
  },
  {
    img: 'https://www.argosy.co.nz/assets/property-images/870_ARGOSY_4_HENDERSON_PL_001_lowres__FocusFillWzEwODAsNjAwLCJ5IiwxNF0.jpg',
    protertyName: '4 Henderson Place, Onehunga',
    org: 'Auckland',
    inductor: 'The property comprises a substantial industrial facility constructed in 1987 and refurbished in 2017. The improvements include a large sprinklered double gable warehouse, two levels of offices, a large canopy and sealed yard area to the northern and eastern portion of the site. The property comprises a large land holding of 21,860 sqm to the eastern periphery of Onehunga, with dual access from Henderson Place and secondary access provided via right of way off Mays Road.',
    Valuation: '$32,600,000',
    WALT: '10.3',
    Area: '10,841',
    Yield: '4.98%',
    position: 'PROPERTY MANAGER',
    positionName: "Meera Sima",
    tel: '021 488 075',
    peoImg: "https://www.argosy.co.nz/assets/people-images/Capture2__FocusFillWzEyMCwxMjAsInkiLDI2XQ.JPG"
  },
  {
    img: 'https://www.argosy.co.nz/assets/property-images/871-2E1A3411-copy__FocusFillWzEwODAsNjAwLCJ5Iiw2MF0.jpg',
    protertyName: '320 Ti Rakau Drive, East Tamaki',
    org: 'Auckland',
    inductor: 'A mixed use complex which incorporates a large distribution warehouse, together with trade retail, offices and a smaller freestanding bulk retail premise. The property is situated with extensive frontage to Ti Rakau Drive, benefitting from resulting exposure.',
    Valuation: '$81,700,000',
    WALT: '6.9',
    Area: '28,353',
    Yield: '5.08%',
    position: 'PROPERTY MANAGER',
    positionName: "Amy Myocevich",
    tel: '021 959 922',
    peoImg: 'https://www.argosy.co.nz/assets/people-images/45I1782_sm-AMY__FocusFillWzEyMCwxMjAsIngiLDMwXQ.jpg'
  },
  {
    img: 'https://www.argosy.co.nz/assets/property-images/729-120419_ARGOSY_MIGHTYAPE_7__FocusFillWzEwODAsNjAwLCJ5Iiw1NV0.jpg',
    protertyName: 'Highgate Parkway, Silverdale',
    org: 'Auckland',
    inductor: 'This property is 22,575sqm of land which is occupied by Mighty Ape’s new 10,500 sqm distribution centre. Thisbuilding was New Zealands 3rd 5 Green Star Industrial Built building. The main energy efficient features are LED lightswithdaylight and occupancy sensors, Increased fresh air rates with CO2 control and air to air heat recovery, heatrecoveryVRF heating and cooling system, low VOC flooring, adhesives and sealants, sustainable timber and peak energydemandreduction.',
    Valuation: '$36,450,000',
    WALT: '6.9',
    Area: '10,581',
    Yield: '4.80%',
    position: 'PROPERTY MANAGER',
    positionName: "Anne Staub",
    tel: '021 488 397',
    peoImg: 'https://www.argosy.co.nz/assets/people-images/45I1751_sm-ANNE__FocusFillWzEyMCwxMjAsIngiLDMwXQ.jpg'
  },
  {
    img: 'https://www.argosy.co.nz/assets/property-images/45I1526_low_res__FocusFillWzEwODAsNjAwLCJ5Iiw2MF0.jpg',
    protertyName: '1 Rothwell Avenue, Albany',
    org: 'Auckland',
    inductor: 'The property comprises a large industrial building constructed circa 1984 providing expansive areas of warehouse with associated recently refurbished offices and showroom.',
    Valuation: '$36,700,000',
    WALT: '9.3',
    Area: '12,683',
    Yield: '4.62%',
    position: 'PROPERTY MANAGER',
    positionName: "Anne Staub",
    tel: '021 488 397',
    peoImg: 'https://www.argosy.co.nz/assets/people-images/45I1751_sm-ANNE__FocusFillWzEyMCwxMjAsIngiLDMwXQ.jpg'
  },
  {
    img: 'https://www.argosy.co.nz/assets/property-images/870_ARGOSY_4_HENDERSON_PL_001_lowres__FocusFillWzEwODAsNjAwLCJ5IiwxNF0.jpg',
    protertyName: '4 Henderson Place, Onehunga',
    org: 'Auckland',
    inductor: 'The property comprises a substantial industrial facility constructed in 1987 and refurbished in 2017. The improvements include a large sprinklered double gable warehouse, two levels of offices, a large canopy and sealed yard area to the northern and eastern portion of the site. The property comprises a large land holding of 21,860 sqm to the eastern periphery of Onehunga, with dual access from Henderson Place and secondary access provided via right of way off Mays Road.',
    Valuation: '$32,600,000',
    WALT: '10.3',
    Area: '10,841',
    Yield: '4.98%',
    position: 'PROPERTY MANAGER',
    positionName: "Meera Sima",
    tel: '021 488 075',
    peoImg: "https://www.argosy.co.nz/assets/people-images/Capture2__FocusFillWzEyMCwxMjAsInkiLDI2XQ.JPG"
  },
  {
    img: 'https://www.argosy.co.nz/assets/property-images/871-2E1A3411-copy__FocusFillWzEwODAsNjAwLCJ5Iiw2MF0.jpg',
    protertyName: '320 Ti Rakau Drive, East Tamaki',
    org: 'Auckland',
    inductor: 'A mixed use complex which incorporates a large distribution warehouse, together with trade retail, offices and a smaller freestanding bulk retail premise. The property is situated with extensive frontage to Ti Rakau Drive, benefitting from resulting exposure.',
    Valuation: '$81,700,000',
    WALT: '6.9',
    Area: '28,353',
    Yield: '5.08%',
    position: 'PROPERTY MANAGER',
    positionName: "Amy Myocevich",
    tel: '021 959 922',
    peoImg: 'https://www.argosy.co.nz/assets/people-images/45I1782_sm-AMY__FocusFillWzEyMCwxMjAsIngiLDMwXQ.jpg'
  },
  {
    img: 'https://www.argosy.co.nz/assets/property-images/729-120419_ARGOSY_MIGHTYAPE_7__FocusFillWzEwODAsNjAwLCJ5Iiw1NV0.jpg',
    protertyName: 'Highgate Parkway, Silverdale',
    org: 'Auckland',
    inductor: 'This property is 22,575sqm of land which is occupied by Mighty Ape’s new 10,500 sqm distribution centre. Thisbuilding was New Zealands 3rd 5 Green Star Industrial Built building. The main energy efficient features are LED lightswithdaylight and occupancy sensors, Increased fresh air rates with CO2 control and air to air heat recovery, heatrecoveryVRF heating and cooling system, low VOC flooring, adhesives and sealants, sustainable timber and peak energydemandreduction.',
    Valuation: '$36,450,000',
    WALT: '6.9',
    Area: '10,581',
    Yield: '4.80%',
    position: 'PROPERTY MANAGER',
    positionName: "Anne Staub",
    tel: '021 488 397',
    peoImg: 'https://www.argosy.co.nz/assets/people-images/45I1751_sm-ANNE__FocusFillWzEyMCwxMjAsIngiLDMwXQ.jpg'
  },
  {
    img: 'https://www.argosy.co.nz/assets/property-images/45I1526_low_res__FocusFillWzEwODAsNjAwLCJ5Iiw2MF0.jpg',
    protertyName: '1 Rothwell Avenue, Albany',
    org: 'Auckland',
    inductor: 'The property comprises a large industrial building constructed circa 1984 providing expansive areas of warehouse with associated recently refurbished offices and showroom.',
    Valuation: '$36,700,000',
    WALT: '9.3',
    Area: '12,683',
    Yield: '4.62%',
    position: 'PROPERTY MANAGER',
    positionName: "Anne Staub",
    tel: '021 488 397',
    peoImg: 'https://www.argosy.co.nz/assets/people-images/45I1751_sm-ANNE__FocusFillWzEyMCwxMjAsIngiLDMwXQ.jpg'
  },
  {
    img: 'https://www.argosy.co.nz/assets/property-images/870_ARGOSY_4_HENDERSON_PL_001_lowres__FocusFillWzEwODAsNjAwLCJ5IiwxNF0.jpg',
    protertyName: '4 Henderson Place, Onehunga',
    org: 'Auckland',
    inductor: 'The property comprises a substantial industrial facility constructed in 1987 and refurbished in 2017. The improvements include a large sprinklered double gable warehouse, two levels of offices, a large canopy and sealed yard area to the northern and eastern portion of the site. The property comprises a large land holding of 21,860 sqm to the eastern periphery of Onehunga, with dual access from Henderson Place and secondary access provided via right of way off Mays Road.',
    Valuation: '$32,600,000',
    WALT: '10.3',
    Area: '10,841',
    Yield: '4.98%',
    position: 'PROPERTY MANAGER',
    positionName: "Meera Sima",
    tel: '021 488 075',
    peoImg: "https://www.argosy.co.nz/assets/people-images/Capture2__FocusFillWzEyMCwxMjAsInkiLDI2XQ.JPG"
  },
  {
    img: 'https://www.argosy.co.nz/assets/property-images/871-2E1A3411-copy__FocusFillWzEwODAsNjAwLCJ5Iiw2MF0.jpg',
    protertyName: '320 Ti Rakau Drive, East Tamaki',
    org: 'Auckland',
    inductor: 'A mixed use complex which incorporates a large distribution warehouse, together with trade retail, offices and a smaller freestanding bulk retail premise. The property is situated with extensive frontage to Ti Rakau Drive, benefitting from resulting exposure.',
    Valuation: '$81,700,000',
    WALT: '6.9',
    Area: '28,353',
    Yield: '5.08%',
    position: 'PROPERTY MANAGER',
    positionName: "Amy Myocevich",
    tel: '021 959 922',
    peoImg: 'https://www.argosy.co.nz/assets/people-images/45I1782_sm-AMY__FocusFillWzEyMCwxMjAsIngiLDMwXQ.jpg'
  },
  {
    img: 'https://www.argosy.co.nz/assets/property-images/729-120419_ARGOSY_MIGHTYAPE_7__FocusFillWzEwODAsNjAwLCJ5Iiw1NV0.jpg',
    protertyName: 'Highgate Parkway, Silverdale',
    org: 'Auckland',
    inductor: 'This property is 22,575sqm of land which is occupied by Mighty Ape’s new 10,500 sqm distribution centre. Thisbuilding was New Zealands 3rd 5 Green Star Industrial Built building. The main energy efficient features are LED lightswithdaylight and occupancy sensors, Increased fresh air rates with CO2 control and air to air heat recovery, heatrecoveryVRF heating and cooling system, low VOC flooring, adhesives and sealants, sustainable timber and peak energydemandreduction.',
    Valuation: '$36,450,000',
    WALT: '6.9',
    Area: '10,581',
    Yield: '4.80%',
    position: 'PROPERTY MANAGER',
    positionName: "Anne Staub",
    tel: '021 488 397',
    peoImg: 'https://www.argosy.co.nz/assets/people-images/45I1751_sm-ANNE__FocusFillWzEyMCwxMjAsIngiLDMwXQ.jpg'
  },
  {
    img: 'https://www.argosy.co.nz/assets/property-images/45I1526_low_res__FocusFillWzEwODAsNjAwLCJ5Iiw2MF0.jpg',
    protertyName: '1 Rothwell Avenue, Albany',
    org: 'Auckland',
    inductor: 'The property comprises a large industrial building constructed circa 1984 providing expansive areas of warehouse with associated recently refurbished offices and showroom.',
    Valuation: '$36,700,000',
    WALT: '9.3',
    Area: '12,683',
    Yield: '4.62%',
    position: 'PROPERTY MANAGER',
    positionName: "Anne Staub",
    tel: '021 488 397',
    peoImg: 'https://www.argosy.co.nz/assets/people-images/45I1751_sm-ANNE__FocusFillWzEyMCwxMjAsIngiLDMwXQ.jpg'
  },
  {
    img: 'https://www.argosy.co.nz/assets/property-images/870_ARGOSY_4_HENDERSON_PL_001_lowres__FocusFillWzEwODAsNjAwLCJ5IiwxNF0.jpg',
    protertyName: '4 Henderson Place, Onehunga',
    org: 'Auckland',
    inductor: 'The property comprises a substantial industrial facility constructed in 1987 and refurbished in 2017. The improvements include a large sprinklered double gable warehouse, two levels of offices, a large canopy and sealed yard area to the northern and eastern portion of the site. The property comprises a large land holding of 21,860 sqm to the eastern periphery of Onehunga, with dual access from Henderson Place and secondary access provided via right of way off Mays Road.',
    Valuation: '$32,600,000',
    WALT: '10.3',
    Area: '10,841',
    Yield: '4.98%',
    position: 'PROPERTY MANAGER',
    positionName: "Meera Sima",
    tel: '021 488 075',
    peoImg: "https://www.argosy.co.nz/assets/people-images/Capture2__FocusFillWzEyMCwxMjAsInkiLDI2XQ.JPG"
  },
  {
    img: 'https://www.argosy.co.nz/assets/property-images/871-2E1A3411-copy__FocusFillWzEwODAsNjAwLCJ5Iiw2MF0.jpg',
    protertyName: '320 Ti Rakau Drive, East Tamaki',
    org: 'Auckland',
    inductor: 'A mixed use complex which incorporates a large distribution warehouse, together with trade retail, offices and a smaller freestanding bulk retail premise. The property is situated with extensive frontage to Ti Rakau Drive, benefitting from resulting exposure.',
    Valuation: '$81,700,000',
    WALT: '6.9',
    Area: '28,353',
    Yield: '5.08%',
    position: 'PROPERTY MANAGER',
    positionName: "Amy Myocevich",
    tel: '021 959 922',
    peoImg: 'https://www.argosy.co.nz/assets/people-images/45I1782_sm-AMY__FocusFillWzEyMCwxMjAsIngiLDMwXQ.jpg'
  },
  {
    img: 'https://www.argosy.co.nz/assets/property-images/729-120419_ARGOSY_MIGHTYAPE_7__FocusFillWzEwODAsNjAwLCJ5Iiw1NV0.jpg',
    protertyName: 'Highgate Parkway, Silverdale',
    org: 'Auckland',
    inductor: 'This property is 22,575sqm of land which is occupied by Mighty Ape’s new 10,500 sqm distribution centre. Thisbuilding was New Zealands 3rd 5 Green Star Industrial Built building. The main energy efficient features are LED lightswithdaylight and occupancy sensors, Increased fresh air rates with CO2 control and air to air heat recovery, heatrecoveryVRF heating and cooling system, low VOC flooring, adhesives and sealants, sustainable timber and peak energydemandreduction.',
    Valuation: '$36,450,000',
    WALT: '6.9',
    Area: '10,581',
    Yield: '4.80%',
    position: 'PROPERTY MANAGER',
    positionName: "Anne Staub",
    tel: '021 488 397',
    peoImg: 'https://www.argosy.co.nz/assets/people-images/45I1751_sm-ANNE__FocusFillWzEyMCwxMjAsIngiLDMwXQ.jpg'
  },
  {
    img: 'https://www.argosy.co.nz/assets/property-images/45I1526_low_res__FocusFillWzEwODAsNjAwLCJ5Iiw2MF0.jpg',
    protertyName: '1 Rothwell Avenue, Albany',
    org: 'Auckland',
    inductor: 'The property comprises a large industrial building constructed circa 1984 providing expansive areas of warehouse with associated recently refurbished offices and showroom.',
    Valuation: '$36,700,000',
    WALT: '9.3',
    Area: '12,683',
    Yield: '4.62%',
    position: 'PROPERTY MANAGER',
    positionName: "Anne Staub",
    tel: '021 488 397',
    peoImg: 'https://www.argosy.co.nz/assets/people-images/45I1751_sm-ANNE__FocusFillWzEyMCwxMjAsIngiLDMwXQ.jpg'
  },
  {
    img: 'https://www.argosy.co.nz/assets/property-images/870_ARGOSY_4_HENDERSON_PL_001_lowres__FocusFillWzEwODAsNjAwLCJ5IiwxNF0.jpg',
    protertyName: '4 Henderson Place, Onehunga',
    org: 'Auckland',
    inductor: 'The property comprises a substantial industrial facility constructed in 1987 and refurbished in 2017. The improvements include a large sprinklered double gable warehouse, two levels of offices, a large canopy and sealed yard area to the northern and eastern portion of the site. The property comprises a large land holding of 21,860 sqm to the eastern periphery of Onehunga, with dual access from Henderson Place and secondary access provided via right of way off Mays Road.',
    Valuation: '$32,600,000',
    WALT: '10.3',
    Area: '10,841',
    Yield: '4.98%',
    position: 'PROPERTY MANAGER',
    positionName: "Meera Sima",
    tel: '021 488 075',
    peoImg: "https://www.argosy.co.nz/assets/people-images/Capture2__FocusFillWzEyMCwxMjAsInkiLDI2XQ.JPG"
  },
  {
    img: 'https://www.argosy.co.nz/assets/property-images/871-2E1A3411-copy__FocusFillWzEwODAsNjAwLCJ5Iiw2MF0.jpg',
    protertyName: '320 Ti Rakau Drive, East Tamaki',
    org: 'Auckland',
    inductor: 'A mixed use complex which incorporates a large distribution warehouse, together with trade retail, offices and a smaller freestanding bulk retail premise. The property is situated with extensive frontage to Ti Rakau Drive, benefitting from resulting exposure.',
    Valuation: '$81,700,000',
    WALT: '6.9',
    Area: '28,353',
    Yield: '5.08%',
    position: 'PROPERTY MANAGER',
    positionName: "Amy Myocevich",
    tel: '021 959 922',
    peoImg: 'https://www.argosy.co.nz/assets/people-images/45I1782_sm-AMY__FocusFillWzEyMCwxMjAsIngiLDMwXQ.jpg'
  },

]


export { data }